spring:
  h2:
    console:
      enabled: true
  allowed:
    resources: /h2-console/**
  datasource:
    hikari.auto-commit: false
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:currency-exchange
    username: sa
    password:
  jpa:
    open-in-view: false
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
logging:
  level:
    org:
      hibernate:
        type: trace